### PR TITLE
4.4.4-8 | Move in xen-44-tools-xendomains-create-lockfile-uncond.patch to xen-queue.am

### PR DESCRIPTION
**Pull request by hughesjr**
4.4.4-6 | Import XSA-180
Backport http://bit.ly/1sSKWqY

### CODE REVIEW

**Comment by gwd** [comment]
Thanks Johnny.  Just wondering, why did you put the xendomains patch as a normal external patch, rather than adding it to xen-queue.am?

**Comment by hughesjr** [comment]
It is easier for me to figure out what is going one if I only put official things (ie, XSAs) in the xen-queue.am patch.

**Comment by gwd** [comment]
Well there are already a fair number of CentOS-specific (aka non-"official" things) in the xen-queue.am.  You can use stgit to move the patches around; and if you give the patches descriptive titles, that should show up even when you import things.

You can 'stg pop' all the XSA-related thing off, then "stg import" this one, then do "stg refresh -e" to give it a proper name and title, preferrably copying the description from the original patch.  That should make things a lot easier to keep track of, rather than essentially storing metadata about the patch in the name and in the spec file.

**Comment by hughesjr** [comment]
4.4.4.4-8 : Move in xen-44-tools-xendomains-create-lockfile-uncond.patch to xen-queue.am

**Pull request merged**
